apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deploymentName }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.deploymentName }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
